### ISSUE TITLE
替换model

### ISSUE THREAD

**Issue by ghost** [dangbo/ncnn-mobile#3]
我想将squeezeNet替换为mobileNet，已经生成好mobileNet.param .bin，接下来应该怎么做呢

**Comment by dangbo** [comment]
ncnn 目前不支持 mobileNet 的

**Comment by ghost** [comment]
@dangbo 能具体说下么，那其他的网络比如alexNet，因为我想多个网络在移动端比较，看一下。是不是要自己写jni程序？还是怎么做

**Comment by dangbo** [comment]
ncnn 目前支持的网络我不清楚哦，你可以在 ncnn 里问一下，jni是通用的，替换模型就可以了。

**Comment by ghost** [comment]
@dangbo 是直接在android工程里替换.param .bin文件么，我没有看到squeezencnn_jni，有可以换模型的地方。非常感谢

**Comment by dangbo** [comment]
直接在 android 工程里替换 .param .bin 文件就可以了。jni 编译为 .so 文件了。

**Comment by jj8401** [comment]
@dangbo 我直接用alexnet的.bin  和.param.bin 替换了，但是程序运行之后就是主界面全黑，连两个按钮都没有，也没报错，是什么情况，只有如下的logcat中的警告 warn

Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.tencent.squeezencnn-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.tencent.squeezencnn-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status

**Comment by ghost** [comment]
@dangbo 我替换为alexnet的模型，但是报错initSqueezeNcnn的错误，应该是.so 文件有问题，您遇到过么

Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20618 (ent.squeezencnn)

**Comment by dangbo** [comment]
这个就不知道了 >_<

**Comment by ghost** [comment]
@dangbo 你是成功替换了么，只添加了两个文件和改了java中的名称

**Comment by dangbo** [comment]
我没有试过其它的网络哦

**Comment by TonyTangYu** [comment]
@jj8401 请问，您现在模型转换成功了吗？
